### PR TITLE
Move relevant parameters from flow to melt pool section

### LINKED ISSUE #211: Rename `TwoPhaseFlowProblem` to `MeltPoolProblem`
... and move it to the `melt_pool` folder. The name `TwoPhaseFlowProblem` seems not reflect the essence of this class anymore (so much has happened since than).

### PR DESCRIPTION
**Pull request by mschreter**
This PR moves the parameters `do_heat_transfer|do_melt_pool|do_evaporation` from the flow section to the melt pool section. Further, I introduced a new `time stepping` parameter category (currently only used within `melt_pool_problem`; the transition of the remaining problems will follow!).

closes #211 

references #170 

@nmuch @peterrum

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by mschreter** [comment]
I miss Travis :-(.

**Comment by peterrum** [comment]
Let me create a GitHub CI instance in release mode. Regarding Travis CI: my hands are tied. I have no permissions there (I cannot even restart runs there).

**Comment by mschreter** [comment]
> Let me create a GitHub CI instance in release mode. Regarding Travis CI: my hands are tied. I have no permissions there (I cannot even restart runs there).

"Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

**Comment by peterrum** [comment]
> "Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

This is annoying. I thought they wanted to keep the free options after migrating from `travis.org` to `travis.com`...

**Pull request merged**
