### PR TITLE
General time stepping section

### LINKED ISSUE #170: Move time integration map to central place
https://github.com/MeltPoolDG/MeltPoolDG/blob/12240021ad1388a2818ae45a228b28430843b18e/include/meltpooldg/advection_diffusion/advection_diffusion_operator.hpp#L18-L22

### PR DESCRIPTION
**Pull request by mschreter**
depends on #261.

closes #170.

FYI @nmuch

### CODE REVIEW

**Comment by peterrum** [comment]
@mschreter Please rebase!

**Comment by mschreter** [comment]
> @mschreter Please rebase!

done :-).

**Comment by mschreter** [comment]
From "local" experience:

- `tests/rotating_bubble_adaflo.json` currently fails. I have no idea why!

**Review by peterrum — APPROVED** [review]
Fine once you have identified the problem!

**Comment by mschreter** [comment]
I've found the issue -.- and will explain it tomorrow.

**Review by peterrum — APPROVED** [review]

**Pull request merged**
