### PR TITLE
Extend film boiling example for 3D

### PR DESCRIPTION
**Pull request by mschreter**
As soon as I have results, I will add a GIF :-).

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by mschreter** [comment]
As promised (I'll try to run the same with simplices):

animation_reduced

**Comment by peterrum** [comment]
... and I hope that I have the slices soon :)

**Comment by mschreter** [comment]
I am sorry @peterrum, currently no simplex support for this example possible due to :-(

https://github.com/MeltPoolDG/MeltPoolDG/blob/af55e63aa5eed9bf4615d772b5d599f4c1720311/source/evaporation/evaporation_source_terms_continuous.cpp#L131-L141

**Comment by peterrum** [comment]
... and I hope I have a solution for that too in this week: I just need to find a mathematician who has an idea how to construct the projection matrix.

**Pull request merged**
